Validate the tag input.

diff --git a/.github/workflows/rave.yml b/.github/workflows/rave.yml
--- a/.github/workflows/rave.yml
+++ b/.github/workflows/rave.yml
@@ -22,7 +22,7 @@ on:
   workflow_dispatch:
     inputs:
       version:
-        description: Full semver tag name for WordPress release in `x.y.z` format.
+        description: Full semver tag name for WordPress release in `x.y.z` format
         required: true
         type: string
 
@@ -39,6 +39,16 @@ jobs:
     outputs:
       version: ${{ steps.fetch.outputs.version }}
     steps:
+      - name: Validate tag input
+        if: ${{ github.event_name == 'workflow_dispatch' }}
+        env:
+          VERSION: ${{ github.event.inputs.version }}
+        run: | #shell
+          if ! grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' <<< "$VERSION"; then
+            echo "Error: Version tag is not in x.y.z format."
+            exit 1
+          fi
+
       - name: Checkout repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
