Verify the stable-check endpoint.

diff --git a/.github/workflows/versions.yml b/.github/workflows/versions.yml
--- a/.github/workflows/versions.yml
+++ b/.github/workflows/versions.yml
@@ -112,3 +112,15 @@ jobs:
             echo "Error: Found a release for next version ($TAG) at $url"
             exit 1
           fi
+
+      - name: Verify the stable-check endpoint
+        if: inputs.package == 'stable-check'
+        env:
+          TAG: ${{ steps.tag.outputs.short }}
+        run: |
+          set -e
+          versions=$(curl -s 'https://api.wordpress.org/core/stable-check/1.0/' | jq -r 'to_entries[].key' | sort -V | tail -n1)
+          if [ "$latest_version" != "$TAG" ]; then
+            echo "Error: Found a newer version ($latest_version) than $TAG"
+            exit 1
+          fi
