Add version verification for WPEngine.

diff --git a/.github/workflows/versions.yml b/.github/workflows/versions.yml
--- a/.github/workflows/versions.yml
+++ b/.github/workflows/versions.yml
@@ -86,3 +86,16 @@ jobs:
             echo "Error: Found a newer version ($latest_version) than $TAG"
             exit 1
           fi
+
+      - name: Verify versions distributed by WPEngine
+        if: inputs.package == 'wpengine-zip'
+        env:
+          TAG: ${{ steps.tag.outputs.next }}
+        run: |
+          set -e
+          url="https://core-updates.wpengine.com/wordpress-${TAG}.zip"
+          status=$(curl -o /dev/null -s -w "%{http_code}" "$url")
+          if [ "$status" != "404" ]; then
+            echo "Error: Found a release for next version ($TAG) at $url"
+            exit 1
+          fi
