Add version verification for Docker.

diff --git a/.github/workflows/versions.yml b/.github/workflows/versions.yml
--- a/.github/workflows/versions.yml
+++ b/.github/workflows/versions.yml
@@ -62,3 +62,15 @@ jobs:
             echo "Error: Found a newer version ($latest_version) than $TAG"
             exit 1
           fi
+
+      - name: Verify versions distributed by Docker
+        if: inputs.package == 'docker-wordpress'
+        env:
+          TAG: ${{ steps.tag.outputs.long }}
+        run: |
+          set -e
+          latest_tag=$(curl -s 'https://hub.docker.com/v2/repositories/library/wordpress/tags?page_size=100' | jq -r '.results[].name' | grep -E '^[0-9]\.[0-9]\.[0-9]$' | sort -V | tail -n1)
+          if [ "$latest_tag" != "$TAG" ]; then
+            echo "Error: Found a newer tag ($latest_tag) than $TAG"
+            exit 1
+          fi
