Add some more checks for distributed versions.

diff --git a/.github/workflows/versions.yml b/.github/workflows/versions.yml
--- a/.github/workflows/versions.yml
+++ b/.github/workflows/versions.yml
@@ -148,6 +148,58 @@ jobs:
             exit 1
           fi
 
+      - name: Verify versions distributed by wordpress.org (zip)
+        if: inputs.package == 'wordpress.org-zip'
+        env:
+          TAG: ${{ steps.tag.outputs.next }}
+        run: |
+          set -e
+          url="https://wordpress.org/wordpress-${TAG}.zip"
+          status=$(curl -o /dev/null -s -w "%{http_code}" "$url")
+          if [ "$status" != "404" ]; then
+            echo "Error: Found a release for next version ($TAG) at $url"
+            exit 1
+          fi
+
+      - name: Verify versions distributed by wordpress.org (tar)
+        if: inputs.package == 'wordpress.org-tar'
+        env:
+          TAG: ${{ steps.tag.outputs.next }}
+        run: |
+          set -e
+          url="https://wordpress.org/wordpress-${TAG}.tar.gz"
+          status=$(curl -o /dev/null -s -w "%{http_code}" "$url")
+          if [ "$status" != "404" ]; then
+            echo "Error: Found a release for next version ($TAG) at $url"
+            exit 1
+          fi
+
+      - name: Verify versions distributed by downloads.wordpress.org (zip)
+        if: inputs.package == 'downloads.wordpress.org-zip'
+        env:
+          TAG: ${{ steps.tag.outputs.next }}
+        run: |
+          set -e
+          url="https://downloads.wordpress.org/release/wordpress-${TAG}.zip"
+          status=$(curl -o /dev/null -s -w "%{http_code}" "$url")
+          if [ "$status" != "404" ]; then
+            echo "Error: Found a release for next version ($TAG) at $url"
+            exit 1
+          fi
+
+      - name: Verify versions distributed by downloads.wordpress.org (tar)
+        if: inputs.package == 'downloads.wordpress.org-tar'
+        env:
+          TAG: ${{ steps.tag.outputs.next }}
+        run: |
+          set -e
+          url="https://downloads.wordpress.org/release/wordpress-${TAG}.tar.gz"
+          status=$(curl -o /dev/null -s -w "%{http_code}" "$url")
+          if [ "$status" != "404" ]; then
+            echo "Error: Found a release for next version ($TAG) at $url"
+            exit 1
+          fi
+
       - name: Fetch stable-check data
         if: inputs.package == 'stable-check'
         uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
